/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisappsv1 "kubeops.dev/petset/apis/apps/v1"
	versioned "kubeops.dev/petset/client/clientset/versioned"
	internalinterfaces "kubeops.dev/petset/client/informers/externalversions/internalinterfaces"
	appsv1 "kubeops.dev/petset/client/listers/apps/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FailoverGroupInformer provides access to a shared informer and lister for
// FailoverGroups.
type FailoverGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() appsv1.FailoverGroupLister
}

type failoverGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewFailoverGroupInformer constructs a new informer for FailoverGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFailoverGroupInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFailoverGroupInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFailoverGroupInformer constructs a new informer for FailoverGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFailoverGroupInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().FailoverGroups().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().FailoverGroups().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().FailoverGroups().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1().FailoverGroups().Watch(ctx, options)
			},
		},
		&apisappsv1.FailoverGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *failoverGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFailoverGroupInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *failoverGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisappsv1.FailoverGroup{}, f.defaultInformer)
}

func (f *failoverGroupInformer) Lister() appsv1.FailoverGroupLister {
	return appsv1.NewFailoverGroupLister(f.Informer().GetIndexer())
}
