/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	appsv1 "kubeops.dev/petset/apis/apps/v1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FailoverGroupLister helps list FailoverGroups.
// All objects returned here must be treated as read-only.
type FailoverGroupLister interface {
	// List lists all FailoverGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1.FailoverGroup, err error)
	// Get retrieves the FailoverGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1.FailoverGroup, error)
	FailoverGroupListerExpansion
}

// failoverGroupLister implements the FailoverGroupLister interface.
type failoverGroupLister struct {
	listers.ResourceIndexer[*appsv1.FailoverGroup]
}

// NewFailoverGroupLister returns a new FailoverGroupLister.
func NewFailoverGroupLister(indexer cache.Indexer) FailoverGroupLister {
	return &failoverGroupLister{listers.New[*appsv1.FailoverGroup](indexer, appsv1.Resource("failovergroup"))}
}
