/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	appsv1 "kubeops.dev/petset/apis/apps/v1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PlacementPolicyLister helps list PlacementPolicies.
// All objects returned here must be treated as read-only.
type PlacementPolicyLister interface {
	// List lists all PlacementPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*appsv1.PlacementPolicy, err error)
	// Get retrieves the PlacementPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*appsv1.PlacementPolicy, error)
	PlacementPolicyListerExpansion
}

// placementPolicyLister implements the PlacementPolicyLister interface.
type placementPolicyLister struct {
	listers.ResourceIndexer[*appsv1.PlacementPolicy]
}

// NewPlacementPolicyLister returns a new PlacementPolicyLister.
func NewPlacementPolicyLister(indexer cache.Indexer) PlacementPolicyLister {
	return &placementPolicyLister{listers.New[*appsv1.PlacementPolicy](indexer, appsv1.Resource("placementpolicy"))}
}
