/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1 "kubeops.dev/petset/apis/apps/v1"
	appsv1 "kubeops.dev/petset/client/clientset/versioned/typed/apps/v1"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakePetSets implements PetSetInterface
type fakePetSets struct {
	*gentype.FakeClientWithList[*v1.PetSet, *v1.PetSetList]
	Fake *FakeAppsV1
}

func newFakePetSets(fake *FakeAppsV1, namespace string) appsv1.PetSetInterface {
	return &fakePetSets{
		gentype.NewFakeClientWithList[*v1.PetSet, *v1.PetSetList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("petsets"),
			v1.SchemeGroupVersion.WithKind("PetSet"),
			func() *v1.PetSet { return &v1.PetSet{} },
			func() *v1.PetSetList { return &v1.PetSetList{} },
			func(dst, src *v1.PetSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PetSetList) []*v1.PetSet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PetSetList, items []*v1.PetSet) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}

// GetScale takes name of the petSet, and returns the corresponding scale object, and an error if there is any.
func (c *fakePetSets) GetScale(ctx context.Context, petSetName string, options metav1.GetOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "scale", petSetName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *fakePetSets) UpdateScale(ctx context.Context, petSetName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (result *autoscalingv1.Scale, err error) {
	emptyResult := &autoscalingv1.Scale{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(c.Resource(), "scale", c.Namespace(), scale, opts), &autoscalingv1.Scale{})

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*autoscalingv1.Scale), err
}
