/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "kubeops.dev/petset/apis/apps/v1"
	scheme "kubeops.dev/petset/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FailoverGroupsGetter has a method to return a FailoverGroupInterface.
// A group's client should implement this interface.
type FailoverGroupsGetter interface {
	FailoverGroups() FailoverGroupInterface
}

// FailoverGroupInterface has methods to work with FailoverGroup resources.
type FailoverGroupInterface interface {
	Create(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.CreateOptions) (*v1.FailoverGroup, error)
	Update(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.UpdateOptions) (*v1.FailoverGroup, error)
	UpdateStatus(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.UpdateOptions) (*v1.FailoverGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.FailoverGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FailoverGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FailoverGroup, err error)
	FailoverGroupExpansion
}

// failoverGroups implements FailoverGroupInterface
type failoverGroups struct {
	client rest.Interface
}

// newFailoverGroups returns a FailoverGroups
func newFailoverGroups(c *AppsV1Client) *failoverGroups {
	return &failoverGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the failoverGroup, and returns the corresponding failoverGroup object, and an error if there is any.
func (c *failoverGroups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.FailoverGroup, err error) {
	result = &v1.FailoverGroup{}
	err = c.client.Get().
		Resource("failovergroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FailoverGroups that match those selectors.
func (c *failoverGroups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FailoverGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FailoverGroupList{}
	err = c.client.Get().
		Resource("failovergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested failoverGroups.
func (c *failoverGroups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("failovergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a failoverGroup and creates it.  Returns the server's representation of the failoverGroup, and an error, if there is any.
func (c *failoverGroups) Create(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.CreateOptions) (result *v1.FailoverGroup, err error) {
	result = &v1.FailoverGroup{}
	err = c.client.Post().
		Resource("failovergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(failoverGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a failoverGroup and updates it. Returns the server's representation of the failoverGroup, and an error, if there is any.
func (c *failoverGroups) Update(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.UpdateOptions) (result *v1.FailoverGroup, err error) {
	result = &v1.FailoverGroup{}
	err = c.client.Put().
		Resource("failovergroups").
		Name(failoverGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(failoverGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *failoverGroups) UpdateStatus(ctx context.Context, failoverGroup *v1.FailoverGroup, opts metav1.UpdateOptions) (result *v1.FailoverGroup, err error) {
	result = &v1.FailoverGroup{}
	err = c.client.Put().
		Resource("failovergroups").
		Name(failoverGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(failoverGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the failoverGroup and deletes it. Returns an error if one occurs.
func (c *failoverGroups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("failovergroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *failoverGroups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("failovergroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched failoverGroup.
func (c *failoverGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FailoverGroup, err error) {
	result = &v1.FailoverGroup{}
	err = c.client.Patch(pt).
		Resource("failovergroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
