/*
Copyright AppsCode Inc. and Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	appsv1 "kubeops.dev/petset/apis/apps/v1"
	scheme "kubeops.dev/petset/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PlacementPoliciesGetter has a method to return a PlacementPolicyInterface.
// A group's client should implement this interface.
type PlacementPoliciesGetter interface {
	PlacementPolicies() PlacementPolicyInterface
}

// PlacementPolicyInterface has methods to work with PlacementPolicy resources.
type PlacementPolicyInterface interface {
	Create(ctx context.Context, placementPolicy *appsv1.PlacementPolicy, opts metav1.CreateOptions) (*appsv1.PlacementPolicy, error)
	Update(ctx context.Context, placementPolicy *appsv1.PlacementPolicy, opts metav1.UpdateOptions) (*appsv1.PlacementPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*appsv1.PlacementPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*appsv1.PlacementPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *appsv1.PlacementPolicy, err error)
	PlacementPolicyExpansion
}

// placementPolicies implements PlacementPolicyInterface
type placementPolicies struct {
	*gentype.ClientWithList[*appsv1.PlacementPolicy, *appsv1.PlacementPolicyList]
}

// newPlacementPolicies returns a PlacementPolicies
func newPlacementPolicies(c *AppsV1Client) *placementPolicies {
	return &placementPolicies{
		gentype.NewClientWithList[*appsv1.PlacementPolicy, *appsv1.PlacementPolicyList](
			"placementpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *appsv1.PlacementPolicy { return &appsv1.PlacementPolicy{} },
			func() *appsv1.PlacementPolicyList { return &appsv1.PlacementPolicyList{} },
		),
	}
}
